[build]
base = "landing"
publish = "/public"
command = "hugo --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://zoom.defensible.ie/phonenumbers"
  to = "https://zoom.us/u/aegmwQNMt5"
  status = 302
  force = true

[[redirects]]
  from = "https://zoom.defensible.ie"
  to = "https://zoom.us/j/8927508943"
  status = 302
  force = true

[[redirects]]
  from = "/beyond_the_soc"
  to = "/beyond_the_soc_part_1"
  status = 302
  force = true
