baseURL: "https://www.defensible.ie/"
languageCode: "en-us"
title: "Defensible Limited"
theme: "PaperMod"
summaryLength: 37
enableGitInfo: true
# buildDrafts: false

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0

markup:
  goldmark:
    renderer:
      unsafe: true

blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Defensible Limited"
  description: "Make it so with independent Information Security, Network Reliability Engineering, and solid no bullshit Technical Marketing from the trenches."
  # keywords: [Blog, Portfolio, PaperMod]
  author: Donal
  # author: ["Me", "You"] # multiple authors
  images: [""] 
  # Images are for Opengraph
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Defensible"
    icon: /logo_bandw.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Is your position Defensible?"
    subtitle: "Make it <strong>so</strong> with independent <strong>Information Security</strong>, <strong>Network Reliability Engineering</strong>, and solid <i>no bullshit</i> <strong>Technical Marketing</strong> from the trenches and by the numbers."
    imageUrl: "/d_logo.png"
    imageWidth: 128
    imageHeight: 128
    imageTitle: Defensible Logo
    buttons:
      - name: Engage
        url: engage
      - name: Pansift
        url: pansift
      - name: iNOG
        url: inog
      - name: Schools
        url: schools

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/makedefensible"
    - name: linkedin
      url: "https://www.linkedin.com/company/is-your-position-defensible/"

  analytics:
    google:
      SiteVerificationTag: "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
    # bing:
      # SiteVerificationTag: "XYZabc"
    # yandex:
      # SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: engage
      name: Engage
      url: /engage/
      weight: 10
    - identifier: PanSift
      name: PanSift
      url: https://pansift.com
      weight: 20
    - identifier: Search
      name: Search
      url: /search/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
